-- MySQL Script generated by MySQL Workbench
-- Wed Nov  5 12:26:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database DB_OPDle
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `DB_OPDle`;
CREATE DATABASE IF NOT EXISTS `DB_OPDle` DEFAULT CHARACTER SET utf8 ;
USE `DB_OPDle` ;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Personaje` (
  `idPersonaje` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Edad` INT NULL,
  `UltimaRecompensa` INT NULL,
  `PrimerArco` VARCHAR(45) NULL,
  `CapituloManga` INT NULL,
  `CapituloAnime` INT NULL,
  `Genero` VARCHAR(45) NULL,
  `Origen` VARCHAR(45) NULL,
  `FotoPersonaje` VARCHAR(500) NULL,
  `Risa` VARCHAR(300) NULL,
  `Personajecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonaje`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Afiliacion` (
  `idAfiliación` INT NOT NULL AUTO_INCREMENT,
  `NombreAfiliacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAfiliación`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Personaje_has_Afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Personaje_has_Afiliacion` (
  `Personaje_idPersonaje` INT NOT NULL,
  `Afiliacion_idAfiliación` INT NOT NULL,
  PRIMARY KEY (`Personaje_idPersonaje`, `Afiliacion_idAfiliación`),
  INDEX `fk_Personaje_has_Afiliacion_Afiliacion1_idx` (`Afiliacion_idAfiliación` ASC) VISIBLE,
  INDEX `fk_Personaje_has_Afiliacion_Personaje_idx` (`Personaje_idPersonaje` ASC) VISIBLE,
  CONSTRAINT `fk_Personaje_has_Afiliacion_Personaje`
    FOREIGN KEY (`Personaje_idPersonaje`)
    REFERENCES `DB_OPDle`.`Personaje` (`idPersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_has_Afiliacion_Afiliacion1`
    FOREIGN KEY (`Afiliacion_idAfiliación`)
    REFERENCES `DB_OPDle`.`Afiliacion` (`idAfiliación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`FrutaDiablo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`FrutaDiablo` (
  `idFrutaDiablo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  `NombreTraducido` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idFrutaDiablo`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Personaje_has_FrutaDiablo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Personaje_has_FrutaDiablo` (
  `Personaje_idPersonaje` INT NOT NULL,
  `FrutaDiablo_ID` INT NOT NULL,
  PRIMARY KEY (`Personaje_idPersonaje`, `FrutaDiablo_ID`),
  INDEX `fk_Personaje_has_FrutaDiablo_FrutaDiablo1_idx` (`FrutaDiablo_ID` ASC) VISIBLE,
  INDEX `fk_Personaje_has_FrutaDiablo_Personaje1_idx` (`Personaje_idPersonaje` ASC) VISIBLE,
  CONSTRAINT `fk_Personaje_has_FrutaDiablo_Personaje1`
    FOREIGN KEY (`Personaje_idPersonaje`)
    REFERENCES `DB_OPDle`.`Personaje` (`idPersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_has_FrutaDiablo_FrutaDiablo1`
    FOREIGN KEY (`FrutaDiablo_ID`)
    REFERENCES `DB_OPDle`.`FrutaDiablo` (`idFrutaDiablo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Haki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Haki` (
  `idHaki` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idHaki`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`Personaje_has_Haki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`Personaje_has_Haki` (
  `Personaje_idPersonaje` INT NOT NULL,
  `Haki_ID` INT NOT NULL,
  PRIMARY KEY (`Personaje_idPersonaje`, `Haki_ID`),
  INDEX `fk_Personaje_has_Haki_Haki1_idx` (`Haki_ID` ASC) VISIBLE,
  INDEX `fk_Personaje_has_Haki_Personaje1_idx` (`Personaje_idPersonaje` ASC) VISIBLE,
  CONSTRAINT `fk_Personaje_has_Haki_Personaje1`
    FOREIGN KEY (`Personaje_idPersonaje`)
    REFERENCES `DB_OPDle`.`Personaje` (`idPersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personaje_has_Haki_Haki1`
    FOREIGN KEY (`Haki_ID`)
    REFERENCES `DB_OPDle`.`Haki` (`idHaki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`CartelRecompensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`CartelRecompensa` (
  `idCartelRecompensa` INT NOT NULL AUTO_INCREMENT,
  `CartelRecompensa` VARCHAR(300) NULL,
  PRIMARY KEY (`idCartelRecompensa`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `DB_OPDle`.`CartelRecompensa_has_Personaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_OPDle`.`CartelRecompensa_has_Personaje` (
  `CartelRecompensa_idCartelRecompensa` INT NOT NULL,
  `Personaje_idPersonaje` INT NOT NULL,
  PRIMARY KEY (`CartelRecompensa_idCartelRecompensa`, `Personaje_idPersonaje`),
  INDEX `fk_CartelRecompensa_has_Personaje_Personaje1_idx` (`Personaje_idPersonaje` ASC) VISIBLE,
  INDEX `fk_CartelRecompensa_has_Personaje_CartelRecompensa1_idx` (`CartelRecompensa_idCartelRecompensa` ASC) VISIBLE,
  CONSTRAINT `fk_CartelRecompensa_has_Personaje_CartelRecompensa1`
    FOREIGN KEY (`CartelRecompensa_idCartelRecompensa`)
    REFERENCES `DB_OPDle`.`CartelRecompensa` (`idCartelRecompensa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CartelRecompensa_has_Personaje_Personaje1`
    FOREIGN KEY (`Personaje_idPersonaje`)
    REFERENCES `DB_OPDle`.`Personaje` (`idPersonaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
